name: Build 28mm Docker

on:
  # schedule:
  #   - cron: '30 22 * * *'
  push:
    branches: none # [ 28mm ]
    # Publish semver tags as releases.
    tags: none # [ 'v0.1.*' ]
  pull_request:
    branches: none # [ 28mm ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.7.0
        
      - name: Download wgrib2
        run: |
          if [ ! -f 3rd-party/wgrib2.tgz ] ; then
            make 3rd-party/wgrib2.tgz
          fi
          
      - name: Set variables
        id: vars
        run: |
          # access with 'echo ${{ steps.vars.outputs.tag }}'
          echo "tag=${GITHUB_REF#refs/*/}" >> ${GITHUB_OUTPUT}
          echo "sha=${GITHUB_SHA}" >> ${GITHUB_OUTPUT}
          echo "repoowner=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_OUTPUT}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ steps.vars.outputs.repoowner }}/28mm-wgrib2
      
      - name: Debug
        run: |
          echo '${{ toJSON(steps.meta.outputs) }}'
          echo
          env | sort
          
      - name: Build builder image
        if: 'false'
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          # Set the desired build target here
          target: 28mm-wgrib2
          push: false
          tags: |
            ${{ steps.vars.outputs.repoowner }}/28mm-wgrib2:${{ github.sha }}
            ${{ steps.vars.outputs.repoowner }}/28mm-wgrib2:${{ steps.vars.outputs.tag }}
            ${{ steps.vars.outputs.repoowner }}/28mm-wgrib2:latest
