name: Docker Image CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the lambda-wgrib2 Docker image
      run: make lambda-wgrib2
    - name: Build the lambda-wgrib2 Docker image
      run: make lambda-pywgrib2
