name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - .github/workflows/docker-image.yml
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: wgrib2
          - image: pywgrib2
            
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    
    - name: Prepare builder in Docker
      run: |
        make 3rd-party/cmake.tgz
        docker build --target builder -t builder:v3.1.2 .
    
    - name: Build the lambda-${{ matrix.image }} Docker image
      run: make lambda-${{ matrix.image }}
