name: New buildx Docker Image CI

on:
  push:
    branches:
        - main
        - refactor-docker-build  
    paths-ignore:
    - .github/workflows/*.yml
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    ## Gleaned from https://docs.docker.com/build/ci/github-actions/local-registry/
    docker-registry:
      runs-on: ubuntu-latest
      services:
        registry:
          image: registry:2
          ports:
            - 5000:5000
      steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry

    foundation:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        needs: 
        - docker-registry
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry
                  
            - name: Setup Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.7.0

            - name: Cache Docker layers
              id: cache-foundation
              uses: actions/cache@v1.2.1
              with:
                path: |
                  /tmp/.buildx-cache
                  ./3rd-party/cmake.tgz
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-buildx
                  
            - name: debug
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                pwd
                echo "List current directory:" && ls -lh && echo
                echo "List ./3rd-party directory:" && ls -lh 3rd-party && echo
                df -h
                
            - name: Download cmake
              if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                make 3rd-party/cmake.tgz
                
            - name: debug
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                pwd
                echo "List current directory:" && ls -lh && echo
                echo "List ./3rd-party directory:" && ls -lh 3rd-party && echo
                df -h
                
            - name: Build foundation image
              uses: docker/build-push-action@v4.1.1
              with:
                context: .
                builder: ${{ steps.buildx.outputs.name }}
                file: Dockerfile
                # Set the desired build target here
                target: foundation
                push: true
                tags: localhost:5000/foundation:latest
                #tags: ${{ steps.prep.outputs.tagged_image }}
                cache-from: type=local,src=/tmp/.buildx-cache
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
                
            - name: Debug docker
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                echo "Docker ps output:" && docker ps -a && echo
                echo "Docker buildx ls output:" && docker buildx ls && echo
                echo "Docker images output:" && docker images --all && echo
                
            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
            
            - name: Inspect foundation
              run: |
                docker buildx imagetools inspect localhost:5000/foundation:latest

    lambda-base:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        needs: 
            - docker-registry
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry
            - name: Setup Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.7.0

            - name: Cache Docker layers
              id: cache-lambda-base
              uses: actions/cache@v1.2.1
              with:
                path: |
                  /tmp/.buildx-cache
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-buildx
                  
            - name: Debug docker
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                echo "Docker ps output:" && docker ps -a && echo
                echo "Docker buildx ls output:" && docker buildx ls && echo

            - name: Build lambda-base image
              uses: docker/build-push-action@v4.1.1
              with:
                context: .
                builder: ${{ steps.buildx.outputs.name }}
                file: Dockerfile
                # Set the desired build target here
                target: lambda-base
                push: true
                tags: localhost:5000/lambda-base:latest
                # tags: ${{ steps.prep.outputs.tagged_image }}
                cache-from: type=local,src=/tmp/.buildx-cache
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            - name: Debug docker
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                echo "Docker ps output:" && docker ps -a && echo
                echo "Docker buildx ls output:" && docker buildx ls && echo
                echo "Docker images output:" && docker images --all && echo
                
            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
            
            - name: Inspect lambda-base
              run: |
                docker buildx imagetools inspect localhost:5000/lambda-base:latest

    builder:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        needs: 
            - foundation
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry
                  
            - name: Setup Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.7.0

            - name: Cache Docker layers
              id: cache-builder
              uses: actions/cache@v1.2.1
              with:
                path: |
                  /tmp/.buildx-cache
                  3rd-party/wgrib2.tgz
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-buildx
          
            - name: Debug docker
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                echo "Docker ps output:" && docker ps -a && echo
                echo "Docker buildx ls output:" && docker buildx ls && echo
                echo "Docker images output:" && docker images --all && echo
                
            - name: Download cmake
              if: steps.cache-builder.outputs.cache-hit != 'true'
              run: |
                make 3rd-party/wgrib2.tgz

            - name: Inspect foundation
              run: |
                docker buildx imagetools inspect localhost:5000/foundation:latest
                
            - name: Build builder image
              uses: docker/build-push-action@v4.1.1
              with:
                context: .
                builder: ${{ steps.buildx.outputs.name }}
                file: Dockerfile
                # Set the desired build target here
                target: builder
                push: true
                tags: localhost:5000/builder:latest
                #tags: ${{ steps.prep.outputs.tagged_image }}
                cache-from: type=local,src=/tmp/.buildx-cache
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            - name: Debug docker
              #if: steps.cache-foundation.outputs.cache-hit != 'true'
              run: |
                echo "Docker ps output:" && docker ps -a && echo
                echo "Docker buildx ls output:" && docker buildx ls && echo
                echo "Docker images output:" && docker images --all && echo
                
            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
            
            - name: Inspect foundation
              run: |
                docker buildx imagetools inspect localhost:5000/foundation:latest

            - name: Inspect builder
              run: |
                docker buildx imagetools inspect localhost:5000/builder:latest

    lambda-wgrib2:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        needs:
            - lambda-base
            - builder
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry
                  
            - name: Setup Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.7.0

            - name: Cache Docker layers
              uses: actions/cache@v1.2.1
              with:
                path: |
                  /tmp/.buildx-cache
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-buildx

            - name: Build lambda-wgrib2 image
              uses: docker/build-push-action@v4.1.1
              with:
                context: .
                builder: ${{ steps.buildx.outputs.name }}
                file: Dockerfile
                # Set the desired build target here
                target: lambda-wgrib2
                push: true
                tags: localhost:5000/lambda-wgrib2:latest
                #tags: ${{ steps.prep.outputs.tagged_image }}
                cache-from: type=local,src=/tmp/.buildx-cache
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
                
            - name: Inspect foundation
              run: |
                docker buildx imagetools inspect localhost:5000/foundation:latest
            
            - name: Inspect lambda-base
              run: |
                docker buildx imagetools inspect localhost:5000/lambda-base:latest

            - name: Inspect builder
              run: |
                docker buildx imagetools inspect localhost:5000/builder:latest
                
            - name: Inspect lambda-wgrib2
              run: |
                docker buildx imagetools inspect localhost:5000/lambda-wgrib2:latest

    lambda-pywgrib2:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        needs:
            - builder
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Cache Docker registry
              id: cache-registry
              uses: actions/cache@v1.2.1
              with:
                path: |
                 /var/lib/docker-registry
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-registry
                  
            - name: Setup Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.7.0

            - name: Cache Docker layers
              uses: actions/cache@v1.2.1
              with:
                path: |
                  /tmp/.buildx-cache
                  ./3rd-party/pywgrib2_s.py
                # Key is named differently to avoid collision
                key: ${{ runner.os }}-al2-buildx-${{ github.job }}
                restore-keys: |
                  ${{ runner.os }}-al2-buildx

            - name: Download pywgrib2_s.py
              if: steps.cache-builder.outputs.cache-hit != 'true'
              run: |
                make 3rd-party/pywgrib2_s.py

            - name: Build lambda-pywgrib2 image
              uses: docker/build-push-action@v4.1.1
              with:
                context: .
                builder: ${{ steps.buildx.outputs.name }}
                file: Dockerfile
                # Set the desired build target here
                target: lambda-pywgrib2
                push: true
                tags: localhost:5000/lambda-pywgrib2:latest
                #tags: ${{ steps.prep.outputs.tagged_image }}
                cache-from: type=local,src=/tmp/.buildx-cache
                # Note the mode=max here
                # More: https://github.com/moby/buildkit#--export-cache-options
                # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
                cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv -v /tmp/.buildx-cache-new /tmp/.buildx-cache
